// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqRIiKoFYB_9RJmc3Wat8I3HPImjJW4M4',
    appId: '1:397916581957:web:bc77a6a71d59ddc3b0732c',
    messagingSenderId: '397916581957',
    projectId: 'blockchain-based-election',
    authDomain: 'blockchain-based-election.firebaseapp.com',
    storageBucket: 'blockchain-based-election.firebasestorage.app',
    measurementId: 'G-L1SER0TZQ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFQmIRwbAQj68oaw2AOl0qWZEuLYyOJ3U',
    appId: '1:397916581957:android:15656b52ac06391fb0732c',
    messagingSenderId: '397916581957',
    projectId: 'blockchain-based-election',
    storageBucket: 'blockchain-based-election.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJN1l5NOl_VJn2aMh-1bFSAX7Mw5JLB9c',
    appId: '1:397916581957:ios:856b508d65e82df7b0732c',
    messagingSenderId: '397916581957',
    projectId: 'blockchain-based-election',
    storageBucket: 'blockchain-based-election.firebasestorage.app',
    iosBundleId: 'com.example.blockchainBasedNationalElectionAdminApp',
  );
}
